apiVersion: v1
kind: Service
metadata:
  name: simplesvc
  namespace: nsscbtest
spec:
  ports:
    - name: canary
      port: 8081
      protocol: TCP
      targetPort: 8081
    - name: reports
      port: 9091
      protocol: TCP
      targetPort: 9091
  selector:
    app: bluegreentest
  type: NodePort
